// For signIn
export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST"
export const SIGN_IN_REQUEST_SUCCESS = "SIGN_IN_REQUEST_SUCCESS"
export const SIGN_IN_REQUEST_FAILURE = "SIGN_IN_REQUEST_FAILURE"

// For signUo
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST"
export const SIGN_UP_REQUEST_SUCCESS = "SIGN_UP_REQUEST_SUCCESS"
export const SIGN_UP_REQUEST_FAILURE = "SIGN_UP_REQUEST_FAILURE"

